name: Test Packaing Jar And Upload

on:
  push:
    branches: [ master ]

jobs:
  build_jar:
    if: ${{ false}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eric2788/maven-jar-publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body-path: changelog.md
  build_readme:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bitflight-devops/github-action-readme-generator@v1.0.12
      with:
        versioning_default_branch: master

